name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted # It uses self hosted runner i.e our ec2 instance
# runs-on: ubuntu-lates will use git hosted runner(means the worker or agent like in jenkins) in order to build ci/cd pipeline

    strategy:
      matrix:
        python-version: [3.12.3]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
